# Jekyll configuration for Farmers Web
title: Farmers Web
description: Premium Quality Grains Direct from Farmers
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude files from processing
exclude:
  - node_modules/
  - server/
  - tools/
  - "*.md"
  - "*.txt"
  - .vscode/
  - .idx/

# Include files that start with underscore
include:
  - .nojekyll

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"